### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [ohlookitsderpy/Mue#32]
Hi...
I Came across your very nice project... As a Logo Designer who really loves to contribute to awesome open source projects, I will love to help use my logo design skills to contribute by creating a unique logo/icon for your project, to give it its own identity.

Currently working on some logo idea concepts that represents your project. I will share the concept here once i complete it, so you can give me your feedback and also changes or tweaks you might want.

Your response will be appreciated...

Regards!

**Comment by ohlookitsderpy** [comment]
Hello!

It would be much appreciated if you could do so, I am interested to see what you come up with.

Thank you so much <3

**Comment by chimzycash** [comment]
I really appreciated your response, I would share the idea concept here once I complete it, so you can give your feedback.

**Comment by chimzycash** [comment]
Hello
Here is the finished logo idea concept... Would love to read your feedback.

Also, you can suggest the preferred color(s) of your choice for the logo.

![LOGO DESIGN_MUE_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/57567849-438d3000-73d7-11e9-9963-768c3fd0c5f1.jpg)
![LOGO DESIGN_MUE_BACKGROUND_3](https://user-images.githubusercontent.com/37814297/57567850-44be5d00-73d7-11e9-846c-272aaf20d942.jpg)
![LOGO DESIGN_MUE_BACKGROUND_4](https://user-images.githubusercontent.com/37814297/57567853-4720b700-73d7-11e9-8119-6e2827d1fe25.jpg)

![LOGO DESIGN_MUE_BACKGROUND_5](https://user-images.githubusercontent.com/37814297/57567845-41c36c80-73d7-11e9-9931-13a0f2548295.jpg)
![LOGO DESIGN_MUE_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/57567847-42f49980-73d7-11e9-8356-7bc18565f760.jpg)

![LOGO DESIGN_MUE_idea concept_NEW](https://user-images.githubusercontent.com/37814297/57567846-425c0300-73d7-11e9-82e0-f45f4de545cb.jpg)

**Comment by ohlookitsderpy** [comment]
That's hot 👍 

As for colour preferences I don't have any, it looks nice!

I would prefer it if you could make the "mue" text have a capital letter at the start.

Thanks <3

**Comment by ohlookitsderpy** [comment]
Oh yeah also, could you upload them in PNG please?

**Comment by chimzycash** [comment]
Glad you like the design... Would make the adjustment on the text and prepare all the files including PNG and Vector files for your use.

**Comment by chimzycash** [comment]
Hi
Here are the updated designs... Would create a Pull Request containing the updated Logo/Icon PNG Files.

![LOGO DESIGN_MUE_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/57589102-eb5d4780-7516-11e9-8c02-d7a36558eb9a.jpg)
![LOGO DESIGN_MUE_BACKGROUND_5](https://user-images.githubusercontent.com/37814297/57589103-ebf5de00-7516-11e9-8d66-cfc62e99d8e4.jpg)

**Comment by ohlookitsderpy** [comment]
Thanks! Closing and merging pr now

**Comment by chimzycash** [comment]
Here is the Google Drive Link with all the files, including the Vector Files for your use.

https://drive.google.com/drive/folders/1jO1Bc0QMyFVc-ZJZs7K8QooBUlqwJ6VF?usp=sharing
